# Generated by Django 5.0.6 on 2024-06-09 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeTutor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student'},
        ),
        migrations.AlterModelOptions(
            name='tutor',
            options={'verbose_name': 'Tutor'},
        ),
        migrations.AddField(
            model_name='student',
            name='is_finding_tutor',
            field=models.BooleanField(default=True),
        ),
    ]
