# Generated by Django 5.0.6 on 2024-06-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeTutor', '0002_alter_student_options_alter_tutor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
