# Generated by Django 5.0.6 on 2024-06-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeTutor', '0004_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='tutor_rates',
            field=models.IntegerField(default=0),
        ),
    ]
