# Generated by Django 5.0.6 on 2024-06-17 06:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeTutor', '0006_userpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='postal_code',
            field=models.IntegerField(default=738090, validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(100000)]),
        ),
    ]
