# Generated by Django 5.0.6 on 2024-06-30 08:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeTutor', '0007_student_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='hourly_rate',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
