# Generated by Django 5.0.6 on 2024-06-30 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CodeTutor', '0008_student_hourly_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='hourly_rate',
            new_name='offered_rate',
        ),
    ]
