# Generated by Django 5.0.6 on 2024-07-06 15:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeTutor', '0008_student_offered_rate_alter_tutor_tutor_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpayment',
            name='count_down',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
