# Generated by Django 5.0.6 on 2024-06-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeTutor', '0009_rename_hourly_rate_student_offered_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='tutor_score',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=4),
        ),
    ]
