# Generated by Django 5.0.6 on 2024-07-06 07:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeTutor', '0012_tutor_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiringapplication',
            name='offered_rates',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
