# Generated by Django 5.0.6 on 2024-07-13 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CodeTutor', '0008_student_offered_rate_alter_tutor_tutor_score'),
        ('CodeTutor', '0014_tutor_evaluators'),
    ]

    operations = [
    ]
