# Generated by Django 5.0.6 on 2024-05-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_room_room_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_code',
        ),
        migrations.AddField(
            model_name='room',
            name='code',
            field=models.CharField(default='9F4A58', max_length=10, unique=True),
        ),
    ]
