# Generated by Django 5.0.6 on 2024-05-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_room_room_code_room_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default='2AFC04', max_length=10, unique=True),
        ),
    ]
