# Generated by Django 5.0.6 on 2024-05-27 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_student_tutor_delete_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='code',
            field=models.CharField(default='78D155', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='code',
            field=models.CharField(default='78D155', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
