# Generated by Django 5.0.6 on 2024-05-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_student_code_alter_tutor_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutor',
            options={'ordering': ['username']},
        ),
        migrations.AddField(
            model_name='student',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default='2006-10-25 14:30:59'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='location',
            field=models.CharField(blank=True, choices=[('N', 'North'), ('NE', 'North East'), ('E', 'East'), ('SE', 'South East'), ('S', 'South'), ('SW', 'South West'), ('W', 'West'), ('NW', 'North West'), ('C', 'Central')], max_length=64),
        ),
        migrations.AddField(
            model_name='tutor',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default='2006-10-25 14:30:59'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='code',
            field=models.CharField(default='A722B3', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='code',
            field=models.CharField(default='A722B3', max_length=10, unique=True),
        ),
    ]
