# Generated by Django 5.0.6 on 2024-05-29 03:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_student_code_alter_tutor_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_qualification', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='tutorScore',
        ),
        migrations.AddField(
            model_name='tutor',
            name='hourly_rate',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AddField(
            model_name='tutor',
            name='students_taught',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tutor',
            name='tutor_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='tutor_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='code',
            field=models.CharField(default='3130BD', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='code',
            field=models.CharField(default='3130BD', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='tutor_qualification',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tutors', to='api.qualification'),
        ),
        migrations.AddField(
            model_name='student',
            name='subjects_required',
            field=models.ManyToManyField(related_name='students', to='api.subject'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='subjects_taught',
            field=models.ManyToManyField(related_name='tutors', to='api.subject'),
        ),
    ]
