# Generated by Django 5.0.6 on 2024-05-29 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_qualification_subject_remove_tutor_tutorscore_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='code',
            field=models.CharField(default='98064B', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='code',
            field=models.CharField(default='98064B', max_length=10, unique=True),
        ),
    ]
