# Generated by Django 5.0.6 on 2024-05-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_student_code_alter_tutor_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='code',
            field=models.CharField(default='2A1B56', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='location',
            field=models.CharField(choices=[('N', 'North'), ('NE', 'North East'), ('E', 'East'), ('SE', 'South East'), ('S', 'South'), ('SW', 'South West'), ('W', 'West'), ('NW', 'North West'), ('C', 'Central')], default='N', max_length=64),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='code',
            field=models.CharField(default='2A1B56', max_length=10, unique=True),
        ),
    ]
