# Generated by Django 5.0.6 on 2024-05-29 12:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_student_code_alter_student_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='code',
            field=models.CharField(default='D60B30', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='code',
            field=models.CharField(default='D60B30', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
