# Generated by Django 5.0.6 on 2024-05-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_student_code_alter_student_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='isStudent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='isStudent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='code',
            field=models.CharField(default='A78166', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='code',
            field=models.CharField(default='A78166', max_length=10, unique=True),
        ),
    ]
