# Generated by Django 5.0.6 on 2024-06-02 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_tutor_tutor_qualification_alter_student_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='tutor_qualification',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='code',
            field=models.CharField(default='9CE736', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='./frontend/static/images'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='code',
            field=models.CharField(default='9CE736', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='./frontend/static/images'),
        ),
    ]
