# Generated by Django 5.0.6 on 2024-06-03 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_tutor_tutor_qualification_alter_student_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tutor',
            options={},
        ),
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
        migrations.RemoveField(
            model_name='student',
            name='username',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='password',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='username',
        ),
        migrations.AddField(
            model_name='student',
            name='user_info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tutor',
            name='user_info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='code',
            field=models.CharField(default='0D7733', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='./uploads/images'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='code',
            field=models.CharField(default='0D7733', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='./uploads/images'),
        ),
    ]
