# Generated by Django 5.0.6 on 2024-06-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_student_options_alter_tutor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='code',
            field=models.CharField(default='384B83', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='code',
            field=models.CharField(default='384B83', max_length=10, unique=True),
        ),
    ]
