# Generated by Django 5.0.6 on 2024-05-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_code',
            field=models.CharField(default='A17300', max_length=10, unique=True),
        ),
    ]
