# Generated by Django 5.0.6 on 2024-05-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_student_code_alter_tutor_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='./uploads/images'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='./uploads/images'),
        ),
        migrations.AlterField(
            model_name='student',
            name='code',
            field=models.CharField(default='2D15D1', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='code',
            field=models.CharField(default='2D15D1', max_length=10, unique=True),
        ),
    ]
