# Generated by Django 5.0.6 on 2024-05-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_student_image_tutor_image_alter_student_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='code',
            field=models.CharField(default='9991CB', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='code',
            field=models.CharField(default='9991CB', max_length=10, unique=True),
        ),
    ]
