# Generated by Django 5.0.6 on 2024-05-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_student_code_alter_tutor_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='code',
            field=models.CharField(default='FB7C6E', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(choices=[('H2_MATHEMATICS', 'H2 Mathematics'), ('H2_PHYSICS', 'H2 Physics'), ('H2_CHEMISTRY', 'H2 Chemistry'), ('H2_ECONOMICS', 'H2 Economics')], max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='code',
            field=models.CharField(default='FB7C6E', max_length=10, unique=True),
        ),
    ]
