# Generated by Django 5.0.6 on 2024-05-29 08:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_student_code_alter_subject_subject_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='code',
            field=models.CharField(default='2C13BB', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_joined',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='code',
            field=models.CharField(default='2C13BB', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='date_joined',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
